# Generated by Django 5.1.2 on 2024-10-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccandidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niradhar',
            name='aadhar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='niradhar',
            name='income_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='niradhar',
            name='passport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='niradhar',
            name='voterid',
            field=models.BooleanField(default=False),
        ),
    ]
