# Generated by Django 5.1.2 on 2024-10-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccandidates', '0002_niradhar_aadhar_niradhar_income_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='niradhar',
            name='pancard',
            field=models.BooleanField(default=False),
        ),
    ]
